### ISSUE TITLE
Discuss if ProjectController should allow anyone to create a proxy

### ISSUE THREAD

**Issue by martriay** [zeppelinos/core#30]
I would like for us to review if and how the `ProjectController` should publicly expose the `create` and `createAndCall` functions.

Pros:
- Anyone can ask for a proxy that uses an implementation registered by the owner

Cons:
- The owner is responsible for tracking, upgrading and paying for the upgrade of every proxy that was created through her `ProjectController` since the user can't
- The owner can upgrade a user-created proxy without the user noticing it. The user should to be fully aware of this.

**Comment by spalladino** [comment]
Keep in mind that other controllers within the app may also need to create new contracts, which is another reason to allow those methods to be open.

**Comment by facuspagnuolo** [comment]
Discussed offline, we prefer keep creation methods public to allow other contracts of a project to create further proxies
